# version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: online_auction_system_app
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: php artisan serve --host=0.0.0.0 --port=8000
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: online_auction_system
            DB_USERNAME: auction_user
            DB_PASSWORD: root

    db:
        image: mysql:5.7
        container_name: online_auction_system_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: online_auction_system
            MYSQL_USER: 'auction_user'
            MYSQL_PASSWORD: 'root'
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: online_auction_system_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: auction_user
            PMA_PASSWORD: 'root'
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    db_data:
